spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jitsi
    username: postgres
    password: coditas
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

app:
  jitsi-base-url: https://meet.jit.si/
  frontend-meet-url: http://localhost:4200/join-meet/
